### ISSUE TITLE
[Feature] Introduce support of cubemaps

### ISSUE THREAD

**Issue by bnoazx005** [bnoazx005/TDEngine2#33]
#### Description 

Cubemaps support should be integrated into the engine.

#### TODO list:

- [x] Define a file with meta information about a cubemap 

- [x] Implement **CBaseCubemapTexture** and **CBaseCubemapLoader**

- [x] Implement **CD3D11CubemapTexture** and **CD3D11CubemapTextureFactory**

- [x] Implement **COGLCubemapTexture** and **COGLCubemapTextureFactory**

**Comment by bnoazx005** [comment]
The latest implementation of the feature is provided within f68881017bed10d559fa28ab7178a006fd461001 commit
