### ISSUE TITLE
[Support] Pre-release checklist

### ISSUE THREAD

**Issue by bnoazx005** [bnoazx005/TDEngine2#71]
#### Checklist

- [x] OpenGL graphics context is fully supported and works
- [x] D3D11 graphics context is fully supported and works
- [x] appveyor builds are built successfully
- [x] travis builds are built successfully
- [x] README.md is updated
- [x] CHANGELOG.md is updated
